name: samba
description: Aplicacion de notas.
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  google_fonts:
  flutter_speed_dial:
  flutter_colorpicker:
  file_picker:
  connectivity_plus:
  internet_connection_checker:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  flutter_launcher_icons:
  flutter_native_splash:

#dart run flutter_launcher_icons
flutter_icons:
  android: true
  image_path: 'assets/icons/icon.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/icons/adaptive_icon.png'

flutter_native_splash:
#dart run flutter_native_splash:create
  #image
  image: assets/icons/icon.png
  #bg color
  color: "#FFFFFF"
  #bg image
  #background_image: assets/images/...


flutter:

  uses-material-design: true
  assets:
    - assets/icons/
